//traducciones en español y en inglés
const i18n = {
    es: {
        nav_video: "EN VIVO",
        nav_fechas: "PRÓXIMAS FECHAS",
        nav_bio: "NOSOTROS",
        nav_relatos: "RELATOS",
        nav_prensa: "PRENSA",
        nav_fotos: "FOTOS",
        nav_contacto: "CONTACTO",
        hero_subtitle: "Orquesta Típica",
        tit_fechas: "PRÓXIMAS FECHAS",
        show_place_1: "La tierra invisible",
        show_detail_1: "21:00 HS - Centenera 1099, CABA",
        show_place_2: "Palacio Libertad",
        show_detail_2: "Sarmiento 151, CABA",
        btn_reservar: "RESERVAR",
        btn_reservar2: "+INFO",
        tit_nosotros: "Sobre nosotros",
        bio_p1: "La Orquesta Invisible es una orquesta de tango contemporáneo de Buenos Aires dirigida por el bandoneonista Julio Coviello, un artista con más de 25 años de trayectoria en la escena del tango argentino.",
        bio_p2: "La agrupación formada por músicos y músicas de diferentes generaciones y vertientes,  reinventa el formato tradicional de la orquesta típica a través de composiciones originales, la creación colectiva y un potente sonido acústico que tiene sus raíces en la Época de Oro del tango, pero impulsado por una energía moderna y urbana.",
        bio_p3: "En su año de debut, el proyecto fue seleccionado para la programación oficial del Festival de Tango de Buenos Aires gracias a la trayectoria de Coviello en agrupaciones fundamentales del género como el Cuarteto Cedrón y la Orquesta Típica Fernández Fierro.",
        bio_p4:"Con una fuerte presencia escénica, un repertorio propio y una visión del tango como patrimonio cultural vivo, la Orquesta Invisible ofrece un sonido argentino auténtico y vanguardista para festivales de world music y escenarios internacionales.",
        tit_relatos: "RELATOS INVISIBLES",
        tit_relato1: "Un arte de tapa de peso",
        epi_relato1: "Con la Orquesta Invisible veníamos pensando cómo podría llamarse el álbum. Nuestro bandoneonista Mariano Burnengo...",
        tit_relato2: "La composición colectiva y la coautoría",
        epi_relato2: "Dentro de la propuesta de Julio para la Orquesta invisible estaba la idea de generar nuevas composiciones en colaboración...",
        tit_relato3: "Audiciones de música, charlas y empanadas",
        epi_relato3: "Todo comenzó el 18 de febrero de 2025, cuando una convocatoria llegó a mis redes sociales: Julio invitaba a formar parte de la Orquesta Invisible...",
        tit_relato4: "Sobre La Tierra Invisible",
        epi_relato4: "La Tierra Invisible es un pequeño boliche ubicado en una ochava del barrio de Parque Chacabuco, en la ciudad de Buenos Aires. Lo conocí allá por el 2022...",
        leer_relato: "LEER RELATO COMPLETO",
        //TRADUCCION RELATOS
        btn_inicio_relatos: '<span class="arrow">←</span> VOLVER AL INICIO',
        // --- RELATO 1: ARTE DE TAPA ---
        encabezado_relato1: "Orquesta Invisible | Un arte de tapa de peso",
        titulo_relato1: "Un arte de tapa de peso",
        subt_relato1: "Buenos Aires, 2026 — Por Julio Coviello",
        p1_relato1: "Con la Orquesta Invisible veníamos pensando cómo podría llamarse el álbum. Nuestro bandoneonista Mariano Burnengo tiró un par de propuestas y el nombre “Huella” empezó a sonar fuerte. El poema “Mi huella” de Atahualpa Yupanqui nos amplió todo el significado.",
        b1_relato1: "¿Cómo puede ser el arte de tapa de un disco de tango llamado “Huella”?",
        p2_relato1: "Pero teníamos un problema. Huella, camino, sendero, son todas palabras que nos remiten a nuestro folklore querido. Pero nuestra huella es por el sendero del tango. ¿Cómo puede ser el arte de tapa de un disco de tango llamado “Huella”? ¿Qué imagen nos puede traer a la ciudad? Ahí lo llamé a Dema, compositor de tangos de Mataderos, artista de arrabal con gran capacidad de síntesis. Y le preguntamos.",
        p3_relato1: "A las dos semanas nos encontramos, y con mucha emoción y muchos gestos nos contó su idea. “La huella tiene que ser en el asfalto, en el hormigón, el nombre de la orquesta escrito con un palito, la huella de un perro o de una bicicleta o de una zapatilla. Esas son las huellas que se hacen en la ciudad.”",
        b2_relato1: "...que el álbum tenga peso. Que la tapa sea una baldosa de hormigón armado, que nos pueda acompañar en cada presentación, que pueda interactuar.",
        p4_relato1: "Que la tapa sea de cemento nos encantó. Se me vino a la mente un concepto de Daniel López: “que el diseño gráfico tenga sustento en kilos, que las ideas tengan peso”. Él es Director de Patrimonio Histórico de la Universidad Nacional de Lanús y construyó con su equipo gran parte del parque de esculturas de la UNLa. Su propuesta es alejarse de lo etéreo de la imagen, materializar. Llevado a nuestra música, que el álbum tenga peso. Que la tapa sea una baldosa de hormigón armado, que nos pueda acompañar en cada presentación, que pueda interactuar.",
        p5_relato1: "Hay cosas que son irremplazables. La era digital no reemplazó al hormigón. La música grabada no reemplazó a la música en vivo. Lo más valioso de las buenas ideas es cuando se pueden llevar adelante. Teníamos que hacer un baldosón de cemento con el nombre de la orquesta y una huella. Un día de marzo, antes de que comiencen las clases, fuimos a la Universidad con Fernando Estrup y Rodrigo Almonacid, (violista y bandoneonista de la Invisible).",
        b3_relato1: "Lo más valioso de las buenas ideas es cuando se pueden llevar adelante.",
        p6_relato1: "Nos recibió Dani López en su taller y nos guió para hacer realidad esta tapa/objeto. Armó un molde, nos hizo cortar una malla de metal, volcar el cemento, alisarlo, para después escribirlo con un palito y pisarlo con una rueda de bicicleta. Una reunión con trabajo, charlas, música e historias vividas donde nació nuestro arte de tapa.",
        // --- RELATO 2: AUDICIONES ---
        encabezado_relato2: "Orquesta Invisible | Audiciones de música, charlas y empanadas",
        titulo_relato2: "Audiciones de música, charlas y empanadas",
        subt_relato2: "Buenos Aires, 2026 — Por Alex Valdés",
        p1_relato2: "Todo comenzó el 18 de febrero de 2025, cuando una convocatoria llegó a mis redes sociales: Julio invitaba a formar parte de la Orquesta Invisible, que empezaría a gestarse en marzo. En ese momento yo estaba terminando un reemplazo como docente de música en un secundario, sentado en la sala de profesores.",
        p2_relato2: "Los ensayos estaban pautados para los miércoles de 11:00 a 14:00, un horario en el que yo daba clases. Sin embargo, el destino pareció acomodar las cosas: la docente titular anunció su regreso y, de pronto, ese horario quedó libre para mí. Hablé con Julio y, aunque tuvimos que posponer la audición porque coincidía con mi último día de reemplazo, a la semana siguiente finalmente pude asistir.",
        b1_relato2: "el destino pareció acomodar las cosas: la docente titular anunció su regreso y, de pronto, ese horario quedó libre para mí.",
        p3_relato2: "Llegué un miércoles de marzo con el contrabajo a La Tierra Invisible. Julio me recibió como anfitrión y ya había varios músicos presentes. Mientras armaba mi instrumento junto al piano, apareció la querida Patricia, con quien había compartido música tiempo atrás en Madero Tango - Iguazú, al norte de Argentina en la provincia de Misiones. Su presencia me llenó de alegría y me dio una confianza extra para la audición.",
        p4_relato2: "Tocamos los temas que nos habían enviado: El Cedrón y la Lechuza y Lengua Seca. Desde el primer momento me impactó la sonoridad y la energía que surgía de esa música. Al finalizar, Julio nos reunió a todos para contarnos la propuesta: tocar mensualmente en La Tierra Invisible, trabajar sobre su repertorio y también componer nuevas piezas durante el año. La idea, además, era registrar todo ese proceso en un disco hacia fin de año.",
        b2_relato2: "Desde el primer momento me impactó la sonoridad y la energía que surgía de esa música.",
        p5_relato2: "Para cerrar la jornada, compartimos unas empanadas, y Julio nos comentó que en los días siguientes se comunicaría con cada uno para confirmar quiénes formarían parte del proyecto. Tres o cuatro días después, recibí su mensaje: había quedado en la Orquesta. La alegría fue enorme. No solo por la música, que me había encantado, sino también por el ambiente humano que se había generado desde el primer encuentro.",
        p6_relato2: "Así fue como, el miércoles siguiente, nos encontramos los seleccionados en el primer ensayo de la nueva Orquesta Invisible. Volvimos a tocar los temas de la audición, pero esta vez sonaban aún más sólidos, más vivos. Luego empezamos a explorar nuevas piezas del repertorio.",
        b3_relato2: "La alegría fue enorme. No solo por la música, que me había encantado, sino también por el ambiente humano que se había generado...",
        p7_relato2: "Con el correr de las semanas, los miércoles se transformaron en un ritual: un espacio de encuentro, de creación y de comunidad. Hacer música, acompañarnos, compartir un mate que circulaba de mano en mano, junto a chipás y galletitas, mientras las conversaciones iban y venían entre múltiples temas.",
        p8_relato2: "Así transcurrieron los ensayos y también las presentaciones en nuestra casa, La Tierra Invisible, ese lugar que se volvió refugio y nos hizo sentir profundamente cobijados. Allí también nacieron tres composiciones propias: Centenera, seguida por Clave Blanca y Ceniza, que terminaron de consolidar el repertorio.",
        p9_relato2: "Durante el año también tuvimos la oportunidad de presentarnos en el Festival de Tango de Buenos Aires, en el Centro Cultural Adan Buenosayres. Y como broche final de 2025, en diciembre entramos al estudio Doctor F para grabar nuestro primer disco. Fueron dos jornadas intensas y hermosas, donde quedó registrada la música de la Orquesta Invisible de ese año.",
        b4_relato2: "Con el correr de las semanas, los miércoles se transformaron en un ritual: un espacio de encuentro, de creación y de comunidad.",
        p10_relato2: "Hoy escribo estas palabras mientras escucho el resultado de todo ese proceso: nuestro primer disco, HUELLA, ya salió a la luz. Desde la distancia, porque volví unos meses a Iguazú. Pero pensando en el regreso para la presentación oficial en Mayo, cuando cumplamos un año de vida.",
        p11_relato2: "Agradezco profundamente a mis compañeros de orquesta —Patricia, Dolores, Fernando, Mabel, Santiago, Paula, Mariano y Rodrigo— y, especialmente, a Julio, por este recorrido y por la felicidad de compartir juntos este proyecto tan significativo.",
        p12_relato2: "Esta es solo una parte de la historia invisible que seguimos escribiendo día a día.",
        // --- RELATO 3: LA COMPOSICIÓN COLECTIVA ---
        encabezado_relato3: "Orquesta Invisible | La composición colectiva",
        titulo_relato3: "La composición colectiva y la coautoría",
        subt_relato3: "Buenos Aires, 2026 — Por Rodrigo Almonacid",
        p1_relato3: "Dentro de la propuesta de Julio para la Orquesta invisible estaba la idea de generar nuevas composiciones en colaboración. Así que en uno de los ensayos propuso armar un tango, donde fue tirando pautas y el que podía aportaba desde su instrumento alguna melodía y una rítmica. Con lo que se fue armando volvió al ensayo siguiente con una idea con más forma y empezó a armarse “Centenera”, el primer tango de la orquesta compuesto de manera colectiva. Se siguieron aportando ideas y Coviello volvía al otro ensayo con las partituras para cada instrumento, hasta que un día lo estrenamos en La Tierra Invisible y todo fue alegría.",
        b1_relato3: "Dentro de la propuesta de Julio para la Orquesta invisible estaba la idea de generar nuevas composiciones en colaboración.",
        p2_relato3: "A la semana siguiente del estreno de “Centenera” Julio envió un mensaje al grupo diciendo que había que empezar con una nueva composición, y preguntó qué se nos ocurría para continuar, ahí fue que Mariano (bandoneonista) dijo que estaría bueno algo más rítmico, con más notas, algo tipo milonga. Ahí fue donde me animé a mostrar algo que había escrito hace muchos años, un intento de candombe donde tenía varias partes armadas pero que le faltaba una buena forma, en eso Fernando (viola) dijo que tenía una milonga también, así que se lo mandamos al director y llegó al ensayo con una parte general donde había acomodado un poco la forma entre mi candombe y la milonga de Fer. Lo empezamos a tocar, grabándolo con el celular Julio iba pidiendo ideas, y así se empezó a gestar el segundo tema compuesto de manera colectiva. Siguieron aportando ideas de contracantos, Mariano escribió una variación, Patricia (pianista) propuso una modulación para un momento del tema y mientras lo ensayabamos las cuerdas empezaban a improvisar algunas voces y efectos propios de sus instrumentos que fueron quedando marcados como parte del arreglo.",
        p3_relato3: "En la siguiente presentación en La Tierra Invisible estrenamos el candombe con el nombre de “Subterráneo” (es el nombre que le había puesto cuando lo escribí 10 años atrás). Tuvo muy buena aceptación del público, pero cuando dijimos el nombre del tema y haciendo referencia a que es un género de nuestros hermanos uruguayos una persona en el público se rió y dijo, “justo subterráneo en Uruguay”, así que ahí me agarró mucha culpa, estuve varios días pensando en que no se tiene que llamar así, propuse a la orquesta buscarle otro nombre, dí mis razones, y todos estuvieron de acuerdo. Entre pedaleos fuí pensando nombres que muestren que lo que estamos haciendo es con respeto, entre ellos se me ocurrió uno cliché como “Cruzando el charco”, otro era “Acá pero de allá” y después me acordé de una linda historia que nos contó nuestro querido director Coviello mientras ensayábamos el candombe y obviamente no nos salía. “A esta clave de candombe la llaman clave blanca, ¿saben por qué la llaman así?, porque es un género netamente afro y cuando se empezó a popularizar en Uruguay la gente quería acompañar el ritmo pero no les salía el que hacian los negros, así que les ensñaban uno mucho más simple, que es el que todos conocemos, y a ese acompañamiento los afro-decendientes le llamaban clave blanca, porque es el ritmo que pueden hacer los blancos”. Con esta historia dando vueltas en mi cabeza se me ocurrió llamarlo así “Clave blanca”, que es una manera de decir que hacemos este género a nuestro entender.",
        b2_relato3: "A esta clave de candombe la llaman clave blanca, ¿saben por qué la llaman así?",
        p4_relato3: "En los siguientes ensayos se fue engrosando el repertorio con temas de Coviello hasta que pasada la mitad del año el dire propone grabar un disco con todo lo que teníamos a fin de año. Todos estuvimos de acuerdo y se empezó a buscar un lugar para grabarlo donde puedan entrar 10 personas tocando a la vez.",
        p5_relato3: "En alguna charla se me ocurre decirle a Julio que tengo unos temas que escribí hace mucho tiempo pero que no le encuentro la manera de seguirlo, y que viendo cómo quedó el candombe trabajado por él me gustaba la idea de pasarle los tangos y ver que se podía hacer. Después de uno de los conciertos en La Tierra Invisible le digo que me gustaría meter en el disco mi tema, a lo que él al día siguiente me pidió que le envíe los archivos, le mandé dos temas, uno que había escrito en 2015 y el otro que era del 2020. Coordinamos un encuentro en su casa y cuando llegué me muestra que los dos temas los hizo uno, estaban en la misma tonalidad, con armonía muy parecida, fuimos al piano y me habló de que eran armonías más bien rockeras, lo cual no estaba mal porque es la música con la que nosotros nos fuimos formando auditivamente y después empezó a buscar una secuencia armónica cercana al tango y tarareando una melodía que se le iba ocurriendo en el momento.",
        b3_relato3: "...fuimos al piano y me habló de que eran armonías más bien rockeras, lo cual no estaba mal porque es la música con la que nosotros nos fuimos formando auditivamente...",
        p6_relato3: "Ahí se empezó a generar “Ceniza”, en 2 semanas el tango nuevo ya estaba armado casi en su totalidad. Todo esto ocurrió a finales de Octubre, para noviembre el estudio de grabación ya estaba elegido y la fecha de grabación confirmada, en menos de un mes lo estrenamos en La Tierra Invisible y unas semanas después lo estábamos grabando.",
        // --- RELATO 4: SOBRE LA TIERRA INVISIBLE ---
        encabezado_relato4: "Orquesta Invisible | Sobre La Tierra Invisible",
        titulo_relato4: "Sobre La Tierra Invisible",
        subt_relato4: "Buenos Aires, 2026 — Por Mariano Burnengo",
        p1_relato4: "La Tierra Invisible es un pequeño boliche ubicado en una ochava del barrio de Parque Chacabuco, en la ciudad de Buenos Aires. Lo conocí allá por el 2022, gracias a Romina Pernigotte, una profesora de tango que daba clases en la previa de la milonga Cañón. Allí mismo supe que era un espacio creado por Julio Coviello, a quien yo ya conocía por su labor como bandoneonista en la mítica Orquesta Fernández Fierro.",
        p2_relato4: "Con el tiempo dejé las clases, pero el boliche se convirtió para mí en una referencia para escuchar tango en vivo. Tuve el privilegio de ver allí a maestros como el Tata Cedrón o el Tape Rubín, e incluso me di el lujo de tocar en una oportunidad con 'Desborde', una orquesta de estudiantes. Curiosamente, aquel fue nuestro último concierto; la orquesta se disolvió poco después, vencida por las dificultades propias de gestionar un grupo de doce personas. Sin embargo, ese final dio paso a un nuevo comienzo.",
        b1_relato4: "Este se convirtió en nuestro refugio de ensayo y en el escenario de nuestro ritual de cada miércoles por la mañana...",
        p3_relato4: "A principios de 2025, La Tierra Invisible vio nacer a la Orquesta Invisible, a la cual me incorporé desde el primer día. Este se convirtió en nuestro refugio de ensayo y en el escenario de nuestro ritual de cada miércoles por la mañana: los primeros en llegar corren las mesas, levantan las persianas, preparan el mate y despliegan los atriles. Me fascina el contraste de este espacio. Los días de ensayo tienen esa crudeza del trabajo compartido, mientras que los días de concierto, una vez al mes, todo luce ordenado y limpio, listo para recibir al público. Es la comodidad de jugar de local. Esta dinámica me remite a la época dorada del tango, cuando cada orquesta tenía su propio club, su estilo y su personalidad. Hoy, este rincón es nuestra trinchera.",
        p4_relato4: "En una era donde el tango no es masivo —tiempos de influencers, streaming y de un contexto político donde el arte suele ser ninguneado—, creo que desde nuestro humilde lugar damos batalla. Hacemos una música que tiene más de cien años y luchamos por mantenerla viva, volviendo a los márgenes: tocando de forma acústica, sin amplificación, para cincuenta personas, encontrándonos en una esquina de Parque Chacabuco para compartir un vino y unas empanadas.",
        b2_relato4: "Hacemos una música que tiene más de cien años y luchamos por mantenerla viva, volviendo a los márgenes",
        p5_relato4: "Siento una especie de nostalgia del presente al saberme partícipe de la historia tanguera actual. En tiempos de globalización, redes sociales e inteligencia artificial, desconozco la dimensión real de nuestro aporte, pero tengo la certeza de que, al menos, habremos dejado nuestra Huella.",
        //PIE
        footsp_relato: "Escuchá la música que inspiró este relato:",
        sp_relato: 'ESCUCHAR "HUELLA" EN SPOTIFY',

        tit_prensa: "PRENSA",
        quote_coviello: '"Y los mayores esfuerzos de la humanidad no fueron esfuerzos por cuestiones económicas, ¿no? Fueron esfuerzos por convicciones, por ideas, por querer cambiar las cosas, por querer dejar plasmada en la realidad una creencia o una idea."',
        date_mayo: "MAYO 2025",
        date_sept: "SEPTIEMBRE 2025",
        date_dic: "DICIEMBRE 2025",
        p_p12: '"En este proyecto jugamos por la camiseta."',
        p_2x4: "Entrevista de radio con Paula Sterczek",
        p_t21: '"La propuesta es que la orquesta “sea invisible” y que cada uno de los integrantes vaya siendo cada vez más visible."',
        p_estoes: '"Hacía rato que tenía ganas de armar una orquesta. Tener un escenario propio para poder ensayar y para poder presentarse es algo que te da tranquilidad e independencia para elegir el repertorio, la música que uno quiere hacer y para bancar los ciclos."',
        p_cultura: '"Seguir las olas de qué es lo que te hace trabajar más o menos, qué es lo que te hace llegar a más gente en Instagram, no siempre te lleva muy lejos, las olas terminan al toque en la playa. Uno quisiera ser una corriente submarina."',
        leer_nota: "LEER NOTA →",
        escuchar: "ESCUCHAR →",
        pk_title: "DESCARGAR PRESS KIT",
        pk_desc: "(PDF, FOTOS HD, RIDER)",
        nav_sp: "SPOTIFY",
        nav_yt: "YOUTUBE",
        footer_contacto: "CONTACTO: orquestatipicainvisible@gmail.com",
        btn_ver_mas: "VER TODAS LAS FECHAS", 
        btn_ver_menos: "VER MENOS",
        btn_prensa_mas: "VER MÁS NOTAS",
        btn_prensa_menos: "VER MENOS"
    },
    en: {
        nav_video: "LIVE",
        nav_fechas: "UPCOMING DATES",
        nav_bio: "ABOUT US",
        nav_relatos: "STORIES",
        nav_prensa: "PRESS",
        nav_fotos: "PHOTOS",
        nav_contacto: "CONTACT",
        hero_subtitle: "Typical Orchestra",
        tit_fechas: "UPCOMING SHOWS",
        show_place_1: "La tierra invisible",
        show_detail_1: "9:00 PM - Centenera 1099, Buenos Aires",
        show_place_2: "Palacio Libertad",
        show_detail_2: "Sarmiento 151, Buenos Aires",
        btn_reservar: "BOOK NOW",
        btn_reservar2: "+INFO",
        tit_nosotros: "About us",
        bio_p1: "La Orquesta Invisible is a contemporary tango orchestra from Buenos Aires led by bandoneonist Julio Coviello, an artist with a career spanning more than 25 years in the Argentine tango scene.",
        bio_p2: "The ensemble, formed by musicians from different generations and backgrounds, reinvents the traditional orquesta típica format through original compositions, collective creation, and a powerful acoustic sound that is rooted in Tango’s Golden Age but driven by a modern and urban energy.",
        bio_p3: "In its debut year, the project was selected for the official programming of the Buenos Aires Tango Festival, thanks to Coviello's trajectory in fundamental groups of the genre such as Cuarteto Cedrón and Orquesta Típica Fernández Fierro.",
        bio_p4: "With a strong stage presence, its own repertoire, and a vision of tango as a living cultural heritage, La Orquesta Invisible offers an authentic and avant-garde Argentine sound for world music festivals and international stages.",
        tit_relatos: "INVISIBLE STORIES",
        tit_relato1: "A heavy-hitting cover art",
        epi_relato1: "With the Orquesta Invisible, we had been thinking about what the album could be called. Our bandoneon player, Mariano Burnengo...",
        tit_relato2: "Collective composition and co-authorship",
        epi_relato2: "Within Julio's proposal for the Orquesta Invisible was the idea of creating new compositions in collaboration...",
        tit_relato3: "Music auditions, talks, and empanadas",
        epi_relato3: "It all started on February 18, 2025, when a call for musicians reached my social media: Julio was inviting people to join the Orquesta Invisible...",
        tit_relato4: "About La Tierra Invisible",
        epi_relato4: "La Tierra Invisible is a small club located on a street corner in the Parque Chacabuco neighborhood, in the city of Buenos Aires. I first discovered it back in 2022...",
        leer_relato: "READ FULL STORY",
        //STORIES
        btn_inicio_relatos: '<span class="arrow">←</span> BACK TO HOME',
        encabezado_relato1: "Orquesta Invisible | A heavy-hitting cover art",
        // --- STORY 1: COVER ART ---
        titulo_relato1: "A heavy-hitting cover art",
        subt_relato1: "Buenos Aires, 2026 — By Julio Coviello",
        p1_relato1: "With the Orquesta Invisible, we had been thinking about what the album could be called. Our bandoneon player Mariano Burnengo suggested a couple of ideas, and the name 'Huella' (Footprint) began to resonate. Atahualpa Yupanqui's poem 'Mi huella' expanded the entire meaning for us.",
        b1_relato1: "How can the cover art for a tango album called 'Huella' look like?",
        p2_relato1: "But we had a problem. Footprint, path, trail—these are all words that remind us of our beloved folklore. But our footprint is on the path of tango. How can the cover art for a tango album called 'Huella' look like? What image can represent the city? That's when I called Dema, a tango composer from Mataderos, a neighborhood artist with a great capacity for synthesis. And we asked him.",
        p3_relato1: "Two weeks later we met, and with great emotion and many gestures, he told us his idea. 'The footprint has to be on the asphalt, in the concrete, the name of the orchestra written with a stick, the footprint of a dog or a bicycle or a sneaker. Those are the footprints made in the city.'",
        b2_relato1: "...that the album has weight. That the cover is a reinforced concrete tile that can accompany us in every performance, that can interact.",
        p4_relato1: "We loved the idea of a cement cover. A concept by Daniel López came to mind: 'that graphic design has weight in kilos, that ideas have weight.' He is the Director of Historical Heritage at the National University of Lanús and, with his team, built much of the UNLa sculpture park. His proposal is to move away from the ethereal nature of the image and materialize it. Applied to our music, let the album have weight. Let the cover be a reinforced concrete tile that can accompany us in every performance, that can interact.",
        p5_relato1: "Some things are irreplaceable. The digital era did not replace concrete. Recorded music did not replace live music. The most valuable thing about good ideas is when they can be carried out. We had to make a cement slab with the orchestra's name and a footprint. One day in March, before classes began, we went to the University with Fernando Estrup and Rodrigo Almonacid (violist and bandoneonist of the Invisible).",
        b3_relato1: "The most valuable thing about good ideas is when they can be carried out.",
        p6_relato1: "Dani López received us in his workshop and guided us to make this cover/object a reality. He set up a mold, had us cut a metal mesh, pour the cement, smooth it out, and then write on it with a stick and step on it with a bicycle wheel. A meeting filled with work, talks, music, and shared stories where our cover art was born.",
        // --- STORY 2: AUDITIONS ---
        encabezado_relato2: "Orquesta Invisible | Music auditions, talks, and empanadas",
        titulo_relato2: "Music auditions, talks, and empanadas",
        subt_relato2: "Buenos Aires, 2026 — By Alex Valdés",
        p1_relato2: "It all started on February 18, 2025, when a call for musicians reached my social media: Julio was inviting people to join the Orquesta Invisible, which would begin to take shape in March. At that moment, I was finishing a substitute teaching position as a music teacher at a high school, sitting in the teachers' lounge.",
        p2_relato2: "Rehearsals were scheduled for Wednesdays from 11:00 AM to 2:00 PM, a time when I was usually teaching. However, fate seemed to arrange things: the regular teacher announced her return, and suddenly, that time slot became free for me. I spoke with Julio, and although we had to postpone the audition because it coincided with my last day of substituting, I was finally able to attend the following week.",
        b1_relato2: "fate seemed to arrange things: the regular teacher announced her return, and suddenly, that time slot became free for me.",
        p3_relato2: "I arrived on a Wednesday in March with my double bass at La Tierra Invisible. Julio welcomed me as the host, and several musicians were already present. While I was setting up my instrument by the piano, the dear Patricia appeared, with whom I had shared music some time ago in Madero Tango - Iguazú, in the north of Argentina in the province of Misiones. Her presence filled me with joy and gave me extra confidence for the audition.",
        p4_relato2: "We played the pieces that had been sent to us: El Cedrón y la Lechuza and Lengua Seca. From the very first moment, I was struck by the sonority and energy arising from that music. At the end, Julio gathered us all to tell us about the proposal: to play monthly at La Tierra Invisible, work on his repertoire, and also compose new pieces during the year. The idea was also to record that entire process on an album towards the end of the year.",
        b2_relato2: "From the very first moment, I was struck by the sonority and energy arising from that music.",
        p5_relato2: "To close the day, we shared some empanadas, and Julio told us that he would contact each of us in the following days to confirm who would be part of the project. Three or four days later, I received his message: I had made it into the Orchestra. The joy was immense. Not only because of the music, which I loved, but also because of the human atmosphere that had been generated desde the very first meeting.",
        p6_relato2: "So it was that, the following Wednesday, the selected musicians met for the first rehearsal of the new Orquesta Invisible. We played the audition pieces again, but this time they sounded even more solid, more alive. Then we began to explore new pieces from the repertoire.",
        b3_relato2: "The joy was immense. Not only because of the music, which I loved, but also because of the human atmosphere that had been generated...",
        p7_relato2: "As the weeks went by, Wednesdays turned into a ritual: a space for encounter, creation, and community. Making music, supporting each other, sharing a mate that circulated from hand to hand, along with chipás and cookies, while conversations flowed between multiple topics.",
        p8_relato2: "That's how the rehearsals went, as well as the performances at our home, La Tierra Invisible, that place that became a refuge and made us feel deeply sheltered. There, three original compositions were also born: Centenera, followed by Clave Blanca and Ceniza, which finished consolidating the repertoire.",
        p9_relato2: "During the year, we also had the opportunity to perform at the Buenos Aires Tango Festival, at the Adan Buenosayres Cultural Center. And as the grand finale of 2025, in December we entered Doctor F studio to record our first album. They were two intense and beautiful days, where the music of the Orquesta Invisible of that year was recorded.",
        b4_relato2: "As the weeks went by, Wednesdays turned into a ritual: a space for encounter, creation, and community.",
        p10_relato2: "Today I write these words while listening to the result of that entire process: our first album, HUELLA, has been released. From a distance, because I returned to Iguazú for a few months. But thinking about the return for the official presentation in May, when we celebrate our first year.",
        p11_relato2: "I am deeply grateful to my orchestra colleagues —Patricia, Dolores, Fernando, Mabel, Santiago, Paula, Mariano, and Rodrigo— and, especially, to Julio, for this journey and for the happiness of sharing this very significant project together.",
        p12_relato2: "This is only a part of the invisible story that we continue to write day by day.",
        // --- STORY 3: COLLECTIVE COMPOSITION ---
        encabezado_relato3: "Orquesta Invisible | Collective composition",
        titulo_relato3: "Collective composition and co-authorship",
        subt_relato3: "Buenos Aires, 2026 — By Rodrigo Almonacid",
        p1_relato3: "Included in Julio's proposal for the Orquesta Invisible was the idea of creating new compositions collaboratively. So, during one of the rehearsals, he suggested putting together a tango, where he provided guidelines and anyone who could contributed a melody or rhythm from their instrument. With what was gathered, he returned to the next rehearsal with a more shaped idea, and 'Centenera' began to take form—the orchestra's first collectively composed tango. Ideas continued to be contributed, and Coviello returned to subsequent rehearsals with scores for each instrument, until one day we premiered it at La Tierra Invisible, and it was pure joy.",
        b1_relato3: "Included in Julio's proposal for the Orquesta Invisible was the idea of creating new compositions collaboratively.",
        p2_relato3: "The week after 'Centenera' premiered, Julio sent a message to the group saying we needed to start a new composition and asked for ideas. Mariano (bandoneonist) suggested something more rhythmic, with more notes, like a milonga. That's when I dared to show something I had written years ago—an attempt at a candombe that had several parts but lacked a solid structure. Fernando (viola) mentioned he had a milonga too, so we sent them to the director. He arrived at the rehearsal with a general draft where he had arranged the structure between my candombe and Fer's milonga. We began playing it, recording it with a phone while Julio asked for ideas, and thus the second collectively composed piece began to take shape. Others contributed counterpoints, Mariano wrote a variation, Patricia (pianist) proposed a modulation for a specific moment, and while we rehearsed, the strings began improvising voices and effects unique to their instruments that eventually became part of the arrangement.",
        p3_relato3: "At our next performance at La Tierra Invisible, we premiered the candombe under the name 'Subterráneo' (the name I had given it when I wrote it 10 years earlier). It was well-received by the audience, but when we announced the title and referenced it as a genre from our Uruguayan brothers, someone in the crowd laughed and said, 'Subway (subterráneo) in Uruguay, of all places.' I felt quite guilty and spent several days thinking the title had to change. I suggested finding another name to the orchestra, gave my reasons, and everyone agreed. While cycling, I thought of names that showed we were approaching the genre with respect—clichés like 'Crossing the River,' another like 'From Here but From There.' Then I remembered a lovely story our director Coviello told us while we were struggling to play the candombe: 'This candombe key is called the white key (clave blanca). Do you know why? Because it's a purely Afro-descendant genre, and when it became popular in Uruguay, people wanted to follow the rhythm but couldn't manage the one the Black community did. So they were taught a much simpler one, the one we all know, and the Afro-descendants called it the white key, because it's the rhythm white people can do.' With this story in mind, I thought of naming it 'Clave Blanca'—a way of saying we perform this genre to the best of our understanding.",
        b2_relato3: "This candombe key is called the white key; do you know why they call it that?",
        p4_relato3: "In following rehearsals, the repertoire grew with Coviello's themes until, past mid-year, the director proposed recording an album with everything we had by the end of the year. We all agreed and began looking for a studio that could fit 10 people playing simultaneously.",
        p5_relato3: "During a conversation, I mentioned to Julio that I had some pieces I'd written long ago but couldn't figure out how to finish. Seeing how the candombe turned out after he worked on it, I liked the idea of handing him the tangos to see what could be done. After one of the concerts at La Tierra Invisible, I told him I'd like to include my track on the album. The next day he asked for the files; I sent two pieces, one from 2015 and another from 2020. We met at his house, and he showed me that he had merged the two into one—they were in the same key with very similar harmony. We went to the piano, and he mentioned they had rock-like harmonies, which wasn't a bad thing since that's the music we grew up listening to. Then he began searching for a harmonic sequence closer to tango, humming a melody as it occurred to him.",
        b3_relato3: "...we went to the piano and he spoke to me about harmonies being rather rock-oriented, which wasn't bad because it's the music we grew up with...",
        p6_relato3: "That's how 'Ceniza' began to emerge; within two weeks, the new tango was almost entirely finished. This all happened at the end of October. By November, the recording studio was chosen and the date confirmed. In less than a month, we premiered it at La Tierra Invisible, and a few weeks later, we were recording it.",
        // --- STORY 4: ABOUT LA TIERRA INVISIBLE ---
        encabezado_relato4: "Orquesta Invisible | About La Tierra Invisible",
        titulo_relato4: "About La Tierra Invisible",
        subt_relato4: "Buenos Aires, 2026 — By Mariano Burnengo",
        p1_relato4: "La Tierra Invisible is a small club located on a street corner in the Parque Chacabuco neighborhood, in the city of Buenos Aires. I discovered it back in 2022, thanks to Romina Pernigotte, a tango teacher who gave classes before the Cañón milonga. It was there that I learned it was a space created by Julio Coviello, whom I already knew for his work as a bandoneonist in the legendary Orquesta Fernández Fierro.",
        p2_relato4: "Over time I left the classes, but the club became a reference point for me to listen to live tango. I had the privilege of seeing masters like Tata Cedrón or Tape Rubín there, and I even had the luxury of playing on one occasion with 'Desborde', a student orchestra. Curiously, that was our last concert; the orchestra disbanded shortly after, overcome by the difficulties inherent in managing a group of twelve people. However, that end gave way to a new beginning.",
        b1_relato4: "This became our rehearsal refuge and the stage for our ritual every Wednesday morning...",
        p3_relato4: "In early 2025, La Tierra Invisible saw the birth of the Orquesta Invisible, which I joined from day one. This became our rehearsal refuge and the stage for our ritual every Wednesday morning: the first to arrive move the tables, lift the shutters, prepare the mate, and set up the music stands. I am fascinated by the contrast of this space. Rehearsal days have that rawness of shared work, while concert days, once a month, everything looks tidy and clean, ready to receive the audience. It's the comfort of playing at home. This dynamic reminds me of the golden age of tango, when each orchestra had its own club, its style, and its personality. Today, this corner is our trench.",
        p4_relato4: "In an era where tango is not mainstream —times of influencers, streaming, and a political context where art is often belittled— I believe that from our humble place we put up a fight. We make music that is over a hundred years old and we struggle to keep it alive by returning to the fringes: playing acoustically, without amplification, for fifty people, meeting on a corner in Parque Chacabuco to share wine and empanadas.",
        b2_relato4: "We make music that is over a hundred years old and we struggle to keep it alive by returning to the fringes",
        p5_relato4: "I feel a kind of nostalgia for the present, knowing I am a participant in current tango history. In times of globalization, social media, and artificial intelligence, I don't know the real dimension of our contribution, but I am certain that, at least, we will have left our Trace (Huella).",
        //FOOT
        footsp_relato: "Listen to the music that inspired this story:",
        sp_relato: 'LISTEN TO "HUELLA" ON SPOTIFY',

        tit_prensa: "PRESS",
        quote_coviello: '"The greatest efforts of humanity were not for economic reasons. They were efforts for convictions, for ideas, for wanting to change things, for wanting to embody a belief or an idea in reality."',
        date_mayo: "MAY 2025",
        date_sept: "SEPTEMBER 2025",
        date_dic: "DECEMBER 2025",
        p_p12: '"In this project, we play for the love of it."',
        p_2x4: "Radio interview with Paula Sterczek",
        p_t21: '"The proposal is for the orchestra to be \"invisible\" so that each of its members can become increasingly visible."',
        p_estoes: '"I had wanted to put together an orchestra for a long time. Having our own stage to rehearse and perform is something that gives you peace of mind and independence to choose the repertoire, the music you want to make, and to sustain the cycles."',
        p_cultura: '"Following the waves of what makes you work more or less, what makes you reach more people on Instagram, doesn\'t always take you very far; the waves end immediately on the beach. One would rather be an underwater current."',
        leer_nota: "READ MORE →",
        escuchar: "LISTEN →",
        pk_title: "DOWNLOAD PRESS KIT",
        pk_desc: "(PDF, HD PHOTOS, RIDER)",
        nav_sp: "SPOTIFY",
        nav_yt: "YOUTUBE",
        footer_contacto: "CONTACT: orquestatipicainvisible@gmail.com",
        btn_ver_mas: "VIEW ALL DATES", 
        btn_ver_menos: "SHOW LESS",
        btn_prensa_mas: "MORE PRESS ARTICLES",
        btn_prensa_menos: "SHOW LESS"
    }
};

function changeLanguage(lang) {
    if (lang !== 'en' && lang !== 'es') lang = 'es';
    localStorage.setItem('selectedLang', lang);
    document.documentElement.lang = lang;

    const elements = document.querySelectorAll('[data-key]');
    elements.forEach(el => {
        const key = el.getAttribute('data-key');
        if (i18n[lang] && i18n[lang][key]) {
            el.innerHTML = i18n[lang][key];
        }
    });

    const btn = document.getElementById('current-lang');
    if (btn) btn.textContent = lang.toUpperCase();
}

function initTranslations() {
    const savedLang = localStorage.getItem('selectedLang') || 'es';
    changeLanguage(savedLang);
}

document.addEventListener('DOMContentLoaded', initTranslations);